service: express-serverless-api
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-3
  memorySize: 128
functions:
  app:
    handler: lambda/lambda.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true